let map = {
  continents: [
    {
      name: "Europe",
      color: "#2c93c4",
      territories: [
        {
          name: "Western Europe",
          top: "Great Britain",
          right: "Southern Europe",
          left: null,
          bottom: null,
          topLeft: null,
          topRight: "Northen Europe",
          bottomLeft: null,
          bottomRight: null,
        },
        {
          name: "Northern Europe",
          top: "Scandinavia",
          right: "Ukraine",
          left: "Great Britain",
          bottom: "Southern Europe",
          topLeft: null,
          topRight: null,
          bottomLeft: "Western Europe",
          bottomRight: null,
        },
        {
          name: "Southern Europe",
          top: "Northern Europe",
          right: null,
          left: "Western Europe",
          bottom: null,
          topLeft: null,
          topRight: "Ukraine",
          bottomLeft: null,
          bottomRight: null,
        },
        {
          name: "Ukraine",
          top: null,
          right: null,
          left: "Northern Europe",
          bottom: null,
          topLeft: "Scandinavia",
          topRight: null,
          bottomLeft: "Sourthern Europe",
          bottomRight: null,
        },
        {
          name: "Scandinavia",
          top: null,
          right: null,
          left: "Iceland",
          bottom: "Northern Europe",
          topLeft: null,
          topRight: null,
          bottomLeft: "Great Britain",
          bottomRight: "Ukraine",
        },
        {
          name: "Iceland",
          top: null,
          right: "Scandinavia",
          left: null,
          bottom: "Great Britain",
          topLeft: null,
          topRight: null,
          bottomLeft: null,
          bottomRight: null,
        },
        {
          name: "Great Britain",
          top: "Iceland",
          right: "Northern Europe",
          left: null,
          bottom: "Western Europe",
          topLeft: null,
          topRight: "Scandinavia",
          bottomLeft: null,
          bottomRight: null,
        },
      ],
    },
    {
      name: "Africa",
      color: "#b15901",
      territories: [
        {
          name: "North Africa",
          top: null,
          right: "East Africa",
          left: null,
          bottom: "Congo",
          topLeft: null,
          topRight: "Egypt",
          bottomLeft: null,
          bottomRight: null,
        },
        {
          name: "Egypt",
          top: null,
          right: null,
          left: null,
          bottom: "East Africa",
          topLeft: null,
          topRight: null,
          bottomLeft: "North Africa",
          bottomRight: null,
        },
        {
          name: "East Africa",
          top: "Egypt",
          right: null,
          left: "North Africa",
          bottom: "South Africa",
          topLeft: null,
          topRight: null,
          bottomLeft: "Congo",
          bottomRight: "Madagascar",
        },
        {
          name: "Congo",
          top: "North Africa",
          right: "South Africa",
          left: null,
          bottom: null,
          topLeft: null,
          topRight: "East Africa",
          bottomLeft: null,
          bottomRight: null,
        },
        {
          name: "South Africa",
          top: "East Africa",
          right: "Madagascar",
          left: "Congo",
          bottom: null,
          topLeft: null,
          topRight: null,
          bottomLeft: null,
          bottomRight: null,
        },
        {
          name: "Madagascar",
          top: null,
          right: null,
          left: "South Africa",
          bottom: null,
          topLeft: "East Africa",
          topRight: null,
          bottomLeft: null,
          bottomRight: null,
        },
      ],
    },
    {
      name: "South America",
      color: "#a72452",
      territories: [
        {
          name: "Venezuela",
          top: null,
          right: null,
          left: null,
          bottom: "Peru",
          topLeft: null,
          topRight: null,
          bottomLeft: null,
          bottomRight: "Brazil",
        },
        {
          name: "Peru",
          top: "Venezuela",
          right: "Brazil",
          left: null,
          bottom: "Argentina",
          topLeft: null,
          topRight: null,
          bottomLeft: null,
          bottomRight: null,
        },
        {
          name: "Brazil",
          top: null,
          right: null,
          left: "Peru",
          bottom: null,
          topLeft: "Venezuela",
          topRight: null,
          bottomLeft: "Argentina",
          bottomRight: null,
        },
        {
          name: "Argentina",
          top: "Peru",
          right: null,
          left: null,
          bottom: null,
          topLeft: null,
          topRight: "Brazil",
          bottomLeft: null,
          bottomRight: null,
        },
      ],
    },
    {
      name: "North America",
      color: "#cfcf51",
      territories: [
        {
          name: "Alaska",
          top: null,
          right: "Northwest Territory",
          left: null,
          bottom: null,
          topLeft: null,
          topRight: null,
          bottomLeft: null,
          bottomRight: "Alberta",
        },
        {
          name: "Northwest Territory",
          top: null,
          right: "Greenland",
          left: "Alaska",
          bottom: "Alberta",
          topLeft: null,
          topRight: null,
          bottomLeft: null,
          bottomRight: "Ontario",
        },
        {
          name: "Alberta",
          top: "Northwest Territory",
          right: "Ontario",
          left: null,
          bottom: "Western US",
          topLeft: "Alaska",
          topRight: null,
          bottomLeft: null,
          bottomRight: null,
        },
        {
          name: "Ontario",
          top: "Greenland",
          right: "Quebec",
          left: "Alberta",
          bottom: "Eastern US",
          topLeft: "Northwest Territory",
          topRight: null,
          bottomLeft: "Western US",
          bottomRight: null,
        },
        {
          name: "Western US",
          top: "Alberta",
          right: "Eastern US",
          left: null,
          bottom: "Central America",
          topLeft: null,
          topRight: "Ontario",
          bottomLeft: null,
          bottomRight: null,
        },
        {
          name: "Eastern US",
          top: "Ontario",
          right: null,
          left: "Western US",
          bottom: null,
          topLeft: null,
          topRight: "Quebec",
          bottomLeft: "Central America",
          bottomRight: null,
        },
        {
          name: "Quebec",
          top: null,
          right: null,
          left: "Ontario",
          bottom: null,
          topLeft: "Greenland",
          topRight: null,
          bottomLeft: "Eastern US",
          bottomRight: null,
        },
        {
          name: "Central America",
          top: "Western US",
          right: null,
          left: null,
          bottom: null,
          topLeft: null,
          topRight: "Eastern US",
          bottomLeft: null,
          bottomRight: null,
        },
        {
          name: "Greenland",
          top: null,
          right: null,
          left: "Northwest Territory",
          bottom: "Ontario",
          topLeft: null,
          topRight: null,
          bottomLeft: null,
          bottomRight: "Quebec",
        },
      ],
    },
    {
      name: "Australia",
      color: "#972efb",
      territories: [
        {
          name: "Indonesia",
          top: null,
          right: "New Guinea",
          left: null,
          bottom: "Western Australia",
          topLeft: null,
          topRight: null,
          bottomLeft: null,
          bottomRight: null,
        },
        {
          name: "New Guinea",
          top: null,
          right: null,
          left: "Indonesia",
          bottom: "Eastern Australia",
          topLeft: null,
          topRight: null,
          bottomLeft: "Western Australia",
          bottomRight: null,
        },
        {
          name: "Western Australia",
          top: "Indonesia",
          right: "Eastern Australia",
          left: null,
          bottom: null,
          topLeft: null,
          topRight: "New Guinea",
          bottomLeft: null,
          bottomRight: null,
        },
        {
          name: "Eastern Australia",
          top: "New Guinea",
          right: null,
          left: "Western Australia",
          bottom: null,
          topLeft: null,
          topRight: null,
          bottomLeft: null,
          bottomRight: null,
        },
      ],
    },
    {
      name: "Asia",
      color: "#38b156",
      territories: [
        {
          name: "Middle East",
          top: null,
          right: "India",
          left: null,
          bottom: null,
          topLeft: null,
          topRight: "Afghanistan",
          bottomLeft: null,
          bottomRight: null,
        },
        {
          name: "India",
          top: "Afghanistan",
          right: "Siam",
          left: "Middle East",
          bottom: null,
          topLeft: null,
          topRight: "China",
          bottomLeft: null,
          bottomRight: null,
        },
        {
          name: "Siam",
          top: "China",
          right: null,
          left: "India",
          bottom: null,
          topLeft: null,
          topRight: null,
          bottomLeft: null,
          bottomRight: null,
        },
        {
          name: "China",
          top: "Siberia",
          right: "Mongolia",
          left: "Afghanistan",
          bottom: "Siam",
          topLeft: "Ural",
          topRight: null,
          bottomLeft: "India",
          bottomRight: null,
        },
        {
          name: "Afghanistan",
          top: "Ural",
          right: "China",
          left: null,
          bottom: "India",
          topLeft: null,
          topRight: null,
          bottomLeft: "Middle East",
          bottomRight: null,
        },
        {
          name: "Ural",
          top: null,
          right: "Siberia",
          left: null,
          bottom: "Afghanistan",
          topLeft: null,
          topRight: null,
          bottomLeft: null,
          bottomRight: "China",
        },
        {
          name: "Mongolia",
          top: "Irkutsk",
          right: "Japan",
          left: "China",
          bottom: null,
          topLeft: "Siberia",
          topRight: "Kamchatka",
          bottomLeft: null,
          bottomRight: null,
        },
        {
          name: "Siberia",
          top: null,
          right: "Irkutsk",
          left: "Ural",
          bottom: "China",
          topLeft: null,
          topRight: "Yakutsk",
          bottomLeft: null,
          bottomRight: "Mongolia",
        },
        {
          name: "Irkutsk",
          top: "Yakutsk",
          right: "Kamchatka",
          left: "Siberia",
          bottom: "Mongolia",
          topLeft: null,
          topRight: null,
          bottomLeft: null,
          bottomRight: null,
        },
        {
          name: "Yakutsk",
          top: null,
          right: null,
          left: null,
          bottom: "Irkutsk",
          topLeft: null,
          topRight: null,
          bottomLeft: "Siberia",
          bottomRight: "Kamchatka",
        },
        {
          name: "Kamchatka",
          top: null,
          right: null,
          left: "Irkutsk",
          bottom: "Japan",
          topLeft: "Yakutsk",
          topRight: null,
          bottomLeft: "Mongolia",
          bottomRight: null,
        },
        {
          name: "Japan",
          top: "Kamchatka",
          right: null,
          left: "Mongolia",
          bottom: null,
          topLeft: null,
          topRight: null,
          bottomLeft: null,
          bottomRight: null,
        },
      ],
    },
  ],
};

export { map };
