let map={
    "continents":[
        {
            "name":"Europe",
            "territories":[
                {
                    "name":"Iceland",
                    "color": "blue",
                    "neighbors":[
                        {
                            "name":"Scandinavia",
                            "degrees":90
                        },
                        {
                            "name":"G.Britain",
                            "degrees":180
                        }
                    ]
                },
                {
                    "name":"Scandinavia",
                    "color": "blue",
                    "neighbors":[
                        {
                            "name":"Iceland",
                            "degrees":270
                        },
                        {
                            "name":"N.Europe",
                            "degrees":180
                        },
                        {
                            "name":"Ukraine",
                            "degrees":135
                        },
                        {
                            "name":"G.Britain",
                            "degrees":225
                        }
                    ]
                },
                {
                    "name":"W.Europe",
                    "color": "blue",
                    "neighbors":[
                        {
                            "name":"G.Britain",
                            "degrees":0
                        },
                        {
                            "name":"S.Europe",
                            "degrees":90
                        },
                        {
                            "name":"N.Europe",
                            "degrees":45
                        }
                    ]
                },
                {
                    "name":"G.Britain",
                    "color": "blue",
                    "neighbors":[
                        {
                            "name":"Iceland",
                            "degrees":0
                        },
                        {
                            "name":"N.Europe",
                            "degrees":90
                        },
                        {
                            "name":"W.Europe",
                            "degrees":180
                        },
                        {
                            "name":"Scandinavia",
                            "degrees":45
                        }
                    ]
                },
                {
                    "name":"S.Europe",
                    "color": "blue",
                    "neighbors":[
                        {
                            "name":"N.Europe",
                            "degrees":0
                        },
                        {
                            "name":"W.Europe",
                            "degrees":270
                        },
                        {
                            "name":"Ukraine",
                            "degrees":45
                        }
                    ]
                },
                {
                    "name":"N.Europe",
                    "color": "blue",
                    "neighbors":[
                        {
                            "name":"Scandinavia",
                            "degrees":0
                        },
                        {
                            "name":"Ukraine",
                            "degrees":90
                        },
                        {
                            "name":"S.Europe",
                            "degrees":180
                        },
                        {
                            "name":"G.Britain",
                            "degrees":270
                        },
                        {
                            "name":"W.Europe",
                            "degrees":225
                        }
                    ]
                },
                {
                    "name":"Ukraine",
                    "color": "blue",
                    "neighbors":[
                        {
                            "name":"N.Europe",
                            "degrees":270
                        },
                        {
                            "name":"Scandinavia",
                            "degrees":45
                        },
                        {
                            "name":"S.Europe",
                            "degrees":225
                        }
                    ]
                }

            ]
        }
    ]
}

export { map };