let territoriesData = {
            
    continents: [
        {
            name: "South America",
            color: "#4E4D3E",
            territories: [
                {
                    name: "Argentina",
                    top: "Peru",
                    right: null,
                    bottom: null,
                    left: null,
                    topLeft: null,
                    topRight: "Brazil",
                    bottomLeft: null,
                    bottomRight: null,
                },
                {
                    name: "Brazil",
                    top: null,
                    right: null,
                    bottom: null,
                    left: "Peru",
                    topLeft: "Venezuela",
                    topRight: null,
                    bottomLeft: "Argentina",
                    bottomRight: null,
                },
                {
                    name: "Venezuela",
                    top: null,
                    right: null,
                    bottom: "Peru",
                    left: null,
                    topLeft: null,
                    topRight: null,
                    bottomLeft: null,
                    bottomRight: "Brazil",
                },
                {
                    name: "Peru",
                    top: "Venezuela",
                    bottom: "Argentina",
                    right: "Brazil",
                    left: null,
                    topLeft: null,
                    topRight: null,
                    bottomLeft: null,
                    bottomRight: null,
                }],
        },
        {
            name: "North America",
            color: "#ED6244",
            territories: [
                {
                    name: "C.America",
                    top: "W.Usa",
                    right: null,
                    bottom: null,
                    left: null,
                    topLeft: null,
                    topRight: "E.Usa",
                    bottomLeft: null,
                    bottomRight: null,
                },
                {
                    name: "W.Usa",
                    top: "Alberta",
                    right: "E.Usa",
                    bottom: "C.America",
                    left: null,
                    topLeft: null,
                    topRight: "Ontario",
                    bottomLeft: null,
                    bottomRight: null,
                },
                {
                    name: "E.Usa",
                    top: "Ontario",
                    right: null,
                    bottom: null,
                    left: "W.Usa",
                    topLeft: null,
                    topRight: "Quebec",
                    bottomLeft: "C.America",
                    bottomRight: null,
                },
                {
                    name: "Alberta",
                    top: "N.Usa",
                    right: "Ontario",
                    bottom: "W.Usa",
                    left: null,
                    topLeft: "Alaska",
                    topRight: null,
                    bottomLeft: null,
                    bottomRight: null,
                },
                {
                    name: "Ontario",
                    top: null,
                    right: "Quebec",
                    bottom: "E.Usa",
                    left: "Alberta",
                    topLeft: "N.Usa",
                    topRight: "Greenland",
                    bottomLeft: "W.Usa",
                    bottomRight: null,
                },
                {
                    name: "Quebec",
                    top: "Greenland",
                    right: null,
                    bottom: null,
                    left: "Ontario",
                    topLeft: null,
                    topRight: null,
                    bottomLeft: "Eastern US",
                    bottomRight: null,
                },
                {
                    name: "Alaska",
                    top: null,
                    right: "N.Usa",
                    bottom: null,
                    left: null,
                    topLeft: null,
                    topRight: null,
                    bottomLeft: null,
                    bottomRight: "Alberta",
                },
                {
                    name: "N.Usa",
                    top: null,
                    right: "Greenland",
                    bottom: "Alberta",
                    left: "Alaska",
                    topLeft: null,
                    topRight: null,
                    bottomLeft: null,
                    bottomRight: "Ontario",
                },
                {
                    name: "Greenland",
                    top: null,
                    right: null,
                    bottom: "Quebec",
                    left: "Northwest Territory",
                    topLeft: null,
                    topRight: null,
                    bottomLeft: "Quebec",
                    bottomRight: null
                },
            ],
        },
        {
            name: "Europe",
            color: "Blue",
            territories: [
                {
                    name: "Iceland",
                    top: null,
                    right: "Scandinavia",
                    bottom: "G.Britain",
                    left: null,
                    topLeft: null,
                    topRight: null,
                    bottomLeft: null,
                    bottomRight: null,
                },
                {
                    name: "G.Britain",
                    top: "Iceland",
                    right: "N.Europe",
                    bottom: "W.Europe",
                    left: null,
                    topLeft: null,
                    topRight: "Scandinavia",
                    bottomLeft: null,
                    bottomRight: null,
                },
                {
                    name: "Scandinavia",
                    top: null,
                    right: null,
                    bottom: "N.Europe",
                    left: "Iceland",
                    topLeft: null,
                    topRight: null,
                    bottomLeft: "G.Britain",
                    bottomRight: "Ukraine",
                },
                {
                    name: "N.Europe",
                    top: "Scandinavia",
                    right: "Ukraine",
                    bottom: "S.Europe",
                    left: "G.Britain",
                    topLeft: null,
                    topRight: null,
                    bottomLeft: "W.Europe",
                    bottomRight: null,
                },
                {
                    name: "W.Europe",
                    top: "G.Britain",
                    right: "S.Europe",
                    bottom: null,
                    left: null,
                    topLeft: null,
                    topRight: "N.Europe",
                    bottomLeft: null,
                    bottomRight: null,
                },
                {
                    name: "S.Europe",
                    top: "N.Europe",
                    right: null,
                    bottom: null,
                    left: "W.Europe",
                    topLeft: null,
                    topRight: "Ukraine",
                    bottomLeft: null,
                    bottomRight: null,
                },
                {
                    name: "Ukraine",
                    top: null,
                    right: null,
                    bottom: null,
                    left: "N.Europe",
                    topLeft: "Scandinavia",
                    topRight: null,
                    bottomLeft: "S.Europe",
                    bottomRight: null,
                },
            ],
        },
        {
            name: "Africa",
            color: "#B67617",
            territories: [
                {
                    name: "N.Africa",
                    top: null,
                    right: "E.Africa",
                    bottom: "Congo",
                    left: null,
                    topLeft: null,
                    topRight: "Egypt",
                    bottomLeft: null,
                    bottomRight: null,
                },
                {
                    name: "Egypt",
                    top: null,
                    right: null,
                    bottom: "E.Africa",
                    left: null,
                    topLeft: null,
                    topRight: null,
                    bottomLeft: "N.Africa",
                    bottomRight: null,
                },
                {
                    name: "E.Africa",
                    top: "Egypt",
                    right: null,
                    bottom: "S.Africa",
                    left: "N.Africa",
                    topLeft: null,
                    topRight: null,
                    bottomLeft: "Congo",
                    bottomRight: "Madagascar",
                },
                {
                    name: "Congo",
                    top: "N.Africa",
                    right: "S.Africa",
                    bottom: null,
                    left: null,
                    topLeft: null,
                    topRight: "E.Africa",
                    bottomLeft: null,
                    bottomRight: null,
                },
                {
                    name: "S.Africa",
                    top: "E.Africa",
                    right: "Madagascar",
                    bottom: null,
                    left: "Congo",
                    topLeft: null,
                    topRight: null,
                    bottomLeft: null,
                    bottomRight: null,
                },
                {
                    name: "Madagascar",
                    top: null,
                    right: null,
                    bottom: null,
                    left: "S.Africa",
                    topLeft: "E.Africa",
                    topRight: null,
                    bottomLeft: null,
                    bottomRight: null,
                },
            ],
        },
        {
            name: "Asia",
            color: "#5FDF64",
            territories: [
                {
                    name: "M.East",
                    top: null,
                    right: "India",
                    bottom: null,
                    left: null,
                    topLeft: null,
                    topRight: "Afghanistan",
                    bottomLeft: null,
                    bottomRight: null,
                },
                {
                    name: "Afghanistan",
                    top: "Ural",
                    right: "China",
                    bottom: "India",
                    left: null,
                    topLeft: null,
                    topRight: null,
                    bottomLeft: "M.East",
                    bottomRight: null,
                },
                {
                    name: "Ural",
                    top: null,
                    right: "Siberia",
                    bottom: "Afghanistan",
                    left: null,
                    topLeft: null,
                    topRight: null,
                    bottomLeft: null,
                    bottomRight: "China",
                },
                {
                    name: "Siberia",
                    top: null,
                    right: "Irkutsk",
                    bottom: "China",
                    left: "Ural",
                    topLeft: null,
                    topRight: "Yakutsk",
                    bottomLeft: null,
                    bottomRight: "Mongolia",
                },
                {
                    name: "Yakutsk",
                    top: null,
                    right: null,
                    bottom: "Irkutsk",
                    left: null,
                    topLeft: null,
                    topRight: null,
                    bottomLeft: "Siberia",
                    bottomRight: "Kamchatka",
                },
                {
                    name: "Irkutsk",
                    top: "Yakutsk",
                    right: "Kamchatka",
                    bottom: "Mongolia",
                    left: "Siberia",
                    topLeft: null,
                    topRight: null,
                    bottomLeft: null,
                    bottomRight: null,
                },
                {
                    name: "Kamchatka",
                    top: null,
                    right: null,
                    bottom: "Japan",
                    left: "Irkutsk",
                    topLeft: "Yakutsk",
                    topRight: null,
                    bottomLeft: "Mongolia",
                    bottomRight: null,
                },
                {
                    name: "Mongolia",
                    top: "Irkutsk",
                    right: "Japan",
                    bottom: null,
                    left: "China",
                    topLeft: "Siberia",
                    topRight: "Kamchatka",
                    bottomLeft: null,
                    bottomRight: null,
                },
                {
                    name: "Japan",
                    top: "Kamchatka",
                    right: null,
                    bottom: null,
                    left: "Mongolia",
                    topLeft: null,
                    topRight: null,
                    bottomLeft: null,
                    bottomRight: null,
                },
                {
                    name: "India",
                    top: "Afghanistan",
                    right: "Siam",
                    bottom: null,
                    left: "M.East",
                    topLeft: null,
                    topRight: "China",
                    bottomLeft: null,
                    bottomRight: null,
                },
                {
                    name: "China",
                    top: "Siberia",
                    right: "Mongolia",
                    bottom: "Siam",
                    left: "Afghanistan",
                    topLeft: "Ural",
                    topRight: null,
                    bottomLeft: "India",
                    bottomRight: null,
                },
                {
                    name: "Siam",
                    top: "China",
                    right: null,
                    bottom: null,
                    left: "India",
                    topLeft: null,
                    topRight: null,
                    bottomLeft: null,
                    bottomRight: null,
                },
            ],
        },
        {
            name: "Australia",
            color: "#BB5FDF",
            territories: [
                {
                    name: "Indonesia",
                    top: null,
                    right: "New Guinea",
                    bottom: "W.Australia",
                    left: null,
                    topLeft: null,
                    topRight: null,
                    bottomLeft: null,
                    bottomRight: null,
                },
                {
                    name: "New Guinea",
                    top: null,
                    right: null,
                    bottom: "E.Australia",
                    left: "Indonesia",
                    topLeft: null,
                    topRight: null,
                    bottomLeft: "W.Australia",
                    bottomRight: null,
                },
                {
                    name: "W.Australia",
                    top: "Indonesia",
                    right: "Eastern Australia",
                    bottom: null,
                    left: null,
                    topLeft: null,
                    topRight: "New Guinea",
                    bottomLeft: null,
                    bottomRight: null,
                },
                {
                    name: "E.Australia",
                    top: "New Guinea",
                    right: null,
                    bottom: null,
                    left: "W.Australia",
                    topLeft: null,
                    topRight: null,
                    bottomLeft: null,
                    bottomRight: null,
                },
            ],
        },
    ],
};

export { territoriesData };